name: MySQL Script on Pull Request

on:
  pull_request:
    branches:
      - staging
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MySQL script (Staging)
        # if: ${{ github.ref == 'refs/heads/staging' }}
        run: |
          echo ${{ github.ref }}
          mysql -h db4free.net -P 3306 -u testcicd -p"${{ secrets.STAGING_MYSQL_PASSWORD }}" < sqlscript.sql

      - name: Run MySQL script (Production)
        if: ${{ github.ref == 'refs/heads/prod' }}
        run: |
          mysql -h db4free.net -P 3306 -u testcicd -p"${{ secrets.PROD_MYSQL_PASSWORD }}" < sqlscript.sql