name: MySQL Script on Pull Request

on:
  pull_request:
    branches:
      - staging
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MySQL script
        run: |
          echo "***"
          echo ${{ github.ref }}
          echo "****"
          echo $GITHUB_HEAD_REF
          echo "****"
          echo $GITHUB_BASE_REF
          if [[ $GITHUB_BASE_REF == 'staging' && $GITHUB_HEAD_REF == 'dev' ]]; then
            mysql -h db4free.net -P 3306 -u testcicd -p"${{ secrets.STAGING_MYSQL_PASSWORD }}" < sqlscript.sql
          fi
          if [[ $GITHUB_BASE_REF == 'prod' && $GITHUB_HEAD_REF == 'staging' ]]; then
            mysql -h db4free.net -P 3306 -u testcicd -p"${{ secrets.PROD_MYSQL_PASSWORD }}" < sqlscript.sql
          fi