name: MySQL Script on Pull Request

on:
  pull_request:
    branches:
      - staging
      - prod

jobs:
  # Codelint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
      
  #     - name: Lint code
  #       uses: github/super-linter@v5
  #       env:
  #         DEFAULT_BRANCH: dev
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  Test:
    runs-on: ubuntu-latest
    #needs: [Codelint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
        #add your code here
        
    
  DeployStaging:
    name: Deploy to staging enviorment
    if: github.event.ref == 'refs/heads/staging'
    needs: [Test]
    environment:
      name: Staging
    env:
      DBHOST: ${{ secrets.SQL_DB_HOST}}
      DBPORT: ${{ secrets.SQL_DB_PORT}}
      DBUSER: ${{ secrets.SQL_DB_USER}}
      DBPASS: ${{ secrets.SQL_DB_PASS}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MySQL script
        run: |
          chmod +x commandscript.sh
          echo "Deploying on SQL using variables in Staging Enviorment"
          echo "$DBHOST"
          echo "$DBPORT"
          echo "$DBUSER"