name: MySQL Script on Pull Request on Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  # Codelint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
      
  #     - name: Lint code
  #       uses: github/super-linter@v5
  #       env:
  #         DEFAULT_BRANCH: dev
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  # Build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Initialize CodeQL
  #       uses: github/codeql-action/init@v2
  #       with:
  #         languages: javascript

  #     # Here is where you build your code
  #     - run: |
  #         # make bootstrap
  #         # make release

  #     - name: Perform CodeQL Analysis
  #       uses: github/codeql-action/analyze@v2
  Test:
    runs-on: ubuntu-latest
    #needs: [Build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
        #add your code here
        
    
  DeployStaging:
    name: Deploy to test enviorment
    #if: github.event.pull_request.merged == 'true'
    needs: [Test]
    environment:
      name: Testing
    env:
      DBHOST: ${{ vars.SQL_DB_HOST }}
      DBPORT: ${{ vars.SQL_DB_PORT }}
      DBUSER: ${{ vars.SQL_DB_USER }}
      DBPASS: ${{ secrets.SQL_DB_PASS }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MySQL script
        run: |
          chmod +x commandscript.sh
          echo "Deploying on SQL using variables in Test Enviorment"
          echo "$DBHOST"
          echo "$DBPORT"
          echo "$DBUSER"
          ./commandscript.sh $DBHOST $DBPORT $DBUSER $DBPASS