name: MySQL Script on Pull Request on Dev

on:
  pull_request:
    branches:
      - prod

jobs:
  # Codelint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
      
  #     - name: Lint code
  #       uses: github/super-linter@v5
  #       env:
  #         DEFAULT_BRANCH: dev
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
  Test:
    runs-on: ubuntu-latest
    #needs: [Codelint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tests
        run: |
        #add your code here
        
    
  DeployStaging:
    name: Deploy to production enviorment
    #if: github.event.pull_request.merged == 'true'
    needs: [Test]
    environment:
      name: Production
    env:
      DBHOST: ${{ secrets.SQL_DB_HOST }}
      DBPORT: ${{ secrets.SQL_DB_PORT }}
      DBUSER: ${{ secrets.SQL_DB_USER }}
      DBPASS: ${{ secrets.SQL_DB_PASS }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run MySQL script
        run: |
          chmod +x commandscript.sh
          echo "Deploying on SQL using variables in Production Enviorment"
          echo "$DBHOST"
          echo "$DBPORT"
          echo "$DBUSER"
          ./commandscript.sh $DBHOST $DBPORT $DBUSER $DBPASS
          